# Generated by Django 2.0.1 on 2018-02-28 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('arch', models.CharField(choices=[('x86_64', 'X86_64'), ('X86_64', 'X86_64'), ('x86', 'X86'), ('X86', 'X86')], max_length=16)),
                ('platform', models.CharField(choices=[('linux', 'LINUX'), ('LINUX', 'LINUX'), ('osx', 'OSX'), ('OSX', 'OSX')], max_length=8)),
                ('channel_path', models.CharField(db_index=True, max_length=255, unique=True)),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('summary', models.TextField(null=True)),
                ('priority_level', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10)])),
                ('is_alive', models.BooleanField(default=True)),
                ('total_pkgs_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'permissions': (('list_channel', 'can list channel instance(s)'),),
                'ordering': ('is_active', 'is_alive', 'channel_name', 'updated_time'),
            },
        ),
        migrations.CreateModel(
            name='CobwebSetting',
            fields=[
                ('setting_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('summary', models.TextField(null=True)),
                ('cobweb_root_prefix', models.CharField(default='/opt/local/cobweb', max_length=255)),
                ('cobweb_platform', models.CharField(choices=[('Linux', 'Linux'), ('linux', 'Linux'), ('osx', 'OSX'), ('OSX', 'OSX'), ('win', 'WIN'), ('WIN', 'WIN')], default='Linux', max_length=8)),
                ('cobweb_arch', models.CharField(choices=[('X86_64', 'X86_64'), ('x86_64', 'x86_64'), ('x86', 'X86'), ('X86', 'X86')], default='X86_64', max_length=8)),
                ('cobweb_home', models.CharField(default='.', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('list_setting', 'can list setting instance(s)'),),
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pkg_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('build', models.CharField(max_length=128, null=True)),
                ('build_number', models.PositiveIntegerField(null=True)),
                ('created_date', models.DateField(null=True)),
                ('license', models.CharField(max_length=255, null=True)),
                ('license_family', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=128)),
                ('size', models.PositiveIntegerField()),
                ('depends', models.TextField(null=True)),
                ('version', models.CharField(max_length=64, null=True)),
                ('pkg_name', models.CharField(max_length=255, unique=True)),
                ('summary', models.TextField(null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('refereces', models.TextField(null=True)),
                ('is_workflow', models.BooleanField(default=False)),
                ('is_cluster_pkg', models.BooleanField(default=False)),
                ('created_author', models.CharField(max_length=64, null=True)),
                ('frontend_templ', models.CharField(max_length=255, null=True)),
                ('output_templ', models.CharField(max_length=255, null=True)),
                ('report_templ', models.CharField(max_length=255, null=True)),
                ('spider_templ', models.CharField(max_length=255, null=True)),
                ('module_templ', models.CharField(max_length=255, null=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('env_name', models.CharField(max_length=255, null=True)),
                ('installed_time', models.DateTimeField(null=True)),
                ('first_channel', models.CharField(max_length=128)),
                ('channels', models.ManyToManyField(to='sscobweb.Channel')),
            ],
            options={
                'permissions': (('list_package', 'can list package instance(s)'),),
                'ordering': ('pkg_name', 'is_installed'),
            },
        ),
    ]
