# Generated by Django 3.0.5 on 2020-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sscobweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('is_active', 'is_alive', 'channel_name', 'updated_time')},
        ),
        migrations.AlterModelOptions(
            name='cobwebsetting',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('pkg_name', 'is_installed')},
        ),
    ]
