# Generated by Django 2.0.1 on 2018-02-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=32)),
                ('total_nodes', models.PositiveIntegerField()),
                ('server_status', models.CharField(max_length=10)),
                ('total_memory_size', models.PositiveIntegerField()),
                ('total_storage_size', models.PositiveIntegerField()),
                ('management_node_uuid', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('cluster_name',),
                'permissions': (('list_cluster', 'can list cluster instance(s)'),),
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('job_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('jobid', models.CharField(max_length=32, unique=True)),
                ('jobname', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=32)),
                ('owner', models.CharField(max_length=32)),
                ('queue', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(null=True)),
                ('qtime', models.DateTimeField(null=True)),
                ('etime', models.DateTimeField(null=True)),
                ('start', models.DateTimeField(db_index=True, null=True)),
                ('end', models.DateTimeField(db_index=True, null=True)),
                ('exec_host', models.TextField(null=True)),
                ('resource_list_neednodes', models.CharField(max_length=256, null=True)),
                ('resource_list_nodect', models.CharField(max_length=256, null=True)),
                ('resource_list_nodes', models.CharField(max_length=256, null=True)),
                ('resource_list_walltime', models.CharField(max_length=16, null=True)),
                ('session', models.CharField(max_length=32, null=True)),
                ('unique_node_count', models.PositiveIntegerField(null=True)),
                ('exit_status', models.IntegerField(null=True)),
                ('resources_used_cput', models.PositiveIntegerField(null=True)),
                ('resources_used_mem', models.PositiveIntegerField(null=True)),
                ('resources_used_vmem', models.PositiveIntegerField(null=True)),
                ('resources_used_walltime', models.CharField(max_length=16, null=True)),
                ('cpus_num', models.PositiveIntegerField(null=True)),
                ('total_execution_slots', models.PositiveIntegerField(null=True)),
                ('cluster_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sscluster.Cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('jobid', 'owner'),
                'permissions': (('list_joblog', 'can list joblog instance(s)'),),
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('item_title', models.CharField(max_length=32)),
                ('item_content', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('checked_status', models.BooleanField(default=False)),
                ('finished_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('checked_status', 'created_time', 'user'),
                'permissions': (('list_todolist', 'can list todolist instance(s)'),),
            },
        ),
    ]
