# Generated by Django 3.0.5 on 2020-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sscluster', '0002_auto_20200407_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ('cluster_name',)},
        ),
        migrations.AlterModelOptions(
            name='joblog',
            options={'ordering': ('jobid', 'owner')},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('checked_status', 'created_time', 'user')},
        ),
    ]
