# -*- coding: utf-8 -*-

# User defined
COBBLER_API_URL = "http://10.157.43.71/cobbler_api"

# You can use 'en' or 'zh', that they means english or chinese, alternatively.
INTERFACE_LANG = 'en'

ZH_INTERFACE = {
    # This path is relative, the absolute path is project_path/sscobbler/static/sscobbler/favicon.png.
    'logo': '/sscobbler/logo-sscobbler.png',
    'website': 'http://super-san.com/index.asp',
    'favicon': '/sscobbler/favicon.png',
    'company_name': r'诺德拓',
    'production_abbr': r'NorData vHPC', 
    'production_name': r'vHPC自动化部署与数据分析平台',
    'production_link': r'http://baidu.com',

    'dashboard': r'仪表盘',
    'system_deploy': r'系统部署',
    'configuration': r'配置与定义',
    'distros': r'Distros',
    'profiles': r'Profiles',
    'systems': r'操作系统',
    'repos': r'软件仓库',
    'images': r'系统镜像',
    'auto_installation_templ': r'自动安装模板',
    'auto_installation_snip': r'自动安装Snippets',
    'mgmtclass': r'管理类',
    'settings': r'设置',
    'resources': r'资源',
    'packages': r'Packages',
    'files': r'Files',
    'actions': r'Actions',
    'import_iso': r'导入ISO',
    'sync': r'同步',
    'reposync': r'同步仓库',
    'hardlink': r'Hardlink',
    'build_iso': r'构建ISO镜像',
    'others': r'其它',
    'check': r'检测',
    'events': r'事件',
    'service_deploy': r'软件/服务部署',
    'monitoring': r'系统与网络监控',
    'documentation': r'使用指南',
    'monitoring_msg': r'监控消息',
    'error_msg': r'错误',
    'warning_msg': r'警告',
    'info_msg': r'信息',
    'quit': r'退出',
    'alert_filter_filed': r'你必须选择用于筛选的字段！',
    'alert_filter_value': r'你必须填写用于筛选的值！',
    'filter': r'筛选',
    'yes': r'是',
    'add_filter': r'添加',
    'save': r'保存',
    'cancel': r'取消',
    'available': r'可获取',
    'selected': r'已选择',
    'welcome': r'欢迎使用',
    'username': r'用户名',
    'passwd': r'密码',
    'login': r'登录',
    'item': r'条目',
    'page': r'页',
}

EN_INTERFACE = {
    # This path is relative, the absolute path is project_path/sscobbler/static/sscobbler/favicon.png.
    'logo': '/sscobbler/logo-sscobbler.png',
    'website': 'http://super-san.com/index.asp',
    'favicon': '/sscobbler/favicon.png',
    'company_name': r'NorData ',
    'production_abbr': r'NorData vHPC', 
    'production_name': r'vHPC Automatic Deployment and Data Analysis Platform',
    'production_link': r'http://baidu.com',

    'dashboard': r'Dashboard',
    'system_deploy': r'System Deployment',
    'configuration': r'Configuration',
    'distros': r'Distros',
    'profiles': r'Profiles',
    'systems': r'Systems',
    'repos': r'Repos',
    'images': r'Images',
    'auto_installation_templ': r'Automatic Installation Templates',
    'auto_installation_snip': r'Automatic Installation Snippets',
    'mgmtclass': r'Management Classes',
    'settings': r'Settings',
    'resources': r'Resources',
    'packages': r'Packages',
    'files': r'Files',
    'actions': r'Actions',
    'import_iso': r'Import ISO',
    'sync': r'Sync',
    'reposync': r'Reposync',
    'hardlink': r'Hardlink',
    'build_iso': r'Build ISO',
    'others': r'Others',
    'check': r'Check',
    'events': r'Events',
    'service_deploy': r'Service Deployment',
    'monitoring': r'Monitoring',
    'documentation': r'Documentation',
    'monitoring_msg': r'Monitoring Messages',
    'error_msg': r'Errors',
    'warning_msg': r'Warnings',
    'info_msg': r'Informations',
    'quit': r'Quit',
    'alert_filter_filed': r'You must select a field to filter on.',
    'alert_filter_value': r'You must select a filter value.',
    'filter': r'Filter',
    'yes': r'On',
    'add_filter': r'Add',
    'save': r'Save',
    'cancel': r'Cancel',
    'available': r'Available',
    'selected': r'Selected',
    'welcome': r'Welcome to Use ',
    'username': r'Username',
    'passwd': r'Password',
    'login': r'Login',
    'item': r'Items',
    'page': r'Pages',
}