# -*- coding: utf-8 -*-

# User defined
COBBLERD_DOMAIN = r'10.157.43.71'
COBBLER_API_URL = "http://" + COBBLERD_DOMAIN + "/cobbler_api"

# You can use 'en' or 'zh', that they means english or chinese, alternatively.
INTERFACE_LANG = 'zh'

COBBLER_USERNAME = 'cobbler'
COBBLER_PASSWORD = 'cobbler'

ZH_INTERFACE = {
    'language': 'zh',
    # This path is relative, the absolute path is project_path/sscobbler/static/sscobbler/favicon.png.
    'logo': 'images/logo-sscobbler.png',
    'website': 'http://super-san.com/index.asp',
    'favicon': 'images/favicon.png',
    'company_name': r'超存',
    'production_abbr': r'SuperSAN vHPC', 
    'production_name': r'vHPC自动化部署与数据分析平台',
    'production_link': r'http://super-san.com/pro.asp?classid=7',
    'actions': r'镜像与软件仓库',
    'add_filter': r'添加',
    'add_interface': r'添加网卡',
    'adding': r'正在添加',
    'alert_filter_filed': r'你必须选择用于筛选的字段！',
    'alert_filter_value': r'你必须填写用于筛选的值！',
    'auto_installation_snip': r'自动安装Snippets',
    'auto_installation_templ': r'自动安装模板',
    'available': r'可获取',
    'batch_actions': r'批量操作',
    'build_iso': r'构建ISO镜像',
    'cancel': r'取消',
    'check': r'检测',
    'configuration': r'配置与定义',
    'copy': r'复制',
    'create_new': r'创建新',
    'create_new_sub': r'创建新子',
    'dashboard': r'仪表盘',
    'delete': r'删除',
    'distros': r'Distros',
    'documentation': r'使用指南',
    'edit': r'编辑',
    'edit_interface': r'编辑网卡',
    'edit_prompt_msg': r'(正在编辑, 值为只读状态)',
    'editing': r'正在编辑',
    'error_msg': r'错误',
    'events': r'任务日志',
    'filename_label': r'文件名',
    'files': r'Files',
    'filter': r'筛选',
    'hardlink': r'Hardlink',
    'images': r'系统镜像',
    'import_iso': r'导入ISO',
    'in_use_warning': r'注意：当前自动化系统安装模板正在使用中。',
    'info_msg': r'信息',
    'interface_num_wmsg': r'System至少要添加一个网卡',
    'ip_address': COBBLERD_DOMAIN,
    'item': r'条目',
    'login': r'登录',
    'mgmtclass': r'管理类',
    'monitoring': r'系统与网络监控',
    'monitoring_msg': r'监控消息',
    'no_perm_wmsg': r'当前用户无权限编辑此对象。',
    'no_snippet_wmsg': r'未指定Snippet名称',
    'others': r'其它',
    'packages': r'Packages',
    'page': r'页',
    'pages': r'页',
    'passwd': r'密码',
    'profiles': r'Profiles',
    'quit': r'退出',
    'really': r'确定吗？',
    'refresh_log': r'刷新日志',
    'rename': r'重命名',
    'rename_interface': r'重命名网卡',
    'repos': r'软件仓库',
    'reposync': r'同步仓库',
    'reset': r'重置',
    'resources': r'资源',
    'save': r'保存',
    'selected': r'已选择',
    'service_deploy': r'软件/服务部署',
    'settings': r'配置',
    'snippet': r'Snippet',
    'snippet_example_msg': r'示例：foo.ks (保存在/var/lib/cobbler/',
    'snippet_label': r'Snippet',
    'sync': r'同步',
    'system_deploy': r'系统部署',
    'systems': r'操作系统',
    'template_label': r'模板',
    'username': r'用户名',
    'view_auto_install_templ': r'查看自动安装模板',
    'warning_msg': r'警告',
    'welcome': r'欢迎使用',
    'yes': r'是',
}

EN_INTERFACE = {
    'language': 'en',
    # This path is relative, the absolute path is project_path/sscobbler/static/sscobbler/favicon.png.
    'logo': 'images/logo-sscobbler.png',
    'website': 'http://super-san.com/index.asp',
    'favicon': 'images/favicon.png',
    'company_name': r'SuperSAN ',
    'production_abbr': r'SuperSAN vHPC', 
    'production_name': r'vHPC Automatic Deployment and Data Analysis Platform',
    'production_link': r'http://super-san.com/pro.asp?classid=7',

    'actions': r'Actions',
    'adding': r'Adding ',
    'add_filter': r'Add',
    'add_interface': r'Add Interface',
    'alert_filter_filed': r'You must select a field to filter on.',
    'alert_filter_value': r'You must select a filter value.',
    'auto_installation_snip': r'Automatic Installation Snippets',
    'auto_installation_templ': r'Automatic Installation Templates',
    'available': r'Available',
    'batch_actions': r'Batch Actions',
    'build_iso': r'Build ISO',
    'cancel': r'Cancel',
    'check': r'Check',
    'configuration': r'Configuration',
    'copy': r'copy',
    'create_new': r'Create new ',
    'create_new_sub': r'Create new sub-',
    'dashboard': r'Dashboard',
    'delete': r'delete',
    'distros': r'Distros',
    'documentation': r'Documentation',
    'edit': r'edit',
    'editing': r'Editing ',
    'edit_interface': r'Edit Interface',
    'edit_prompt_msg': r'(editing, value is read-only)',
    'error_msg': r'Errors',
    'events': r'Events Log',
    'filename_label': r'Filename',
    'files': r'Files',
    'filter': r'Filter',
    'hardlink': r'Hardlink',
    'images': r'Images',
    'import_iso': r'Import ISO',
    'info_msg': r'Informations',
    'interface_num_wmsg': r'systems must always have at least one interface.',
    'in_use_warning': r'NOTE: This automatic OS installation template is currently in-use.',
    'ip_address': COBBLERD_DOMAIN,
    'item': r'Items',
    'login': r'Login',
    'mgmtclass': r'Management Classes',
    'monitoring': r'Monitoring',
    'monitoring_msg': r'Monitoring Messages',
    'no_perm_wmsg': r'This user does not have permissions to edit this object.',
    'no_snippet_wmsg': r'NO SNIPPET NAME SPECIFIED',
    'others': r'Others',
    'packages': r'Packages',
    'page': r'Page',
    'pages': r'Pages',
    'passwd': r'Password',
    'profiles': r'Profiles',
    'quit': r'Quit',
    'really': r'Really?',
    'refresh_log': r'Refresh log',
    'rename': r'rename',
    'rename_interface': r'Rename Interface',
    'repos': r'Repos',
    'reposync': r'Reposync',
    'reset': r'Reset',
    'resources': r'Resources',
    'save': r'Save',
    'selected': r'Selected',
    'service_deploy': r'Service Deployment',
    'settings': r'Settings',
    'snippet': r' a Snippet',
    'snippet_example_msg': r'Example:  foo.ks (to be saved in /var/lib/cobbler/',
    'snippet_label': r'Snippet',
    'sync': r'Sync',
    'systems': r'Systems',
    'system_deploy': r'System Deployment',
    'template_label': r'Template',
    'username': r'Username',
    'view_auto_install_templ': r'View automatic installation template',
    'warning_msg': r'Warnings',
    'welcome': r'Welcome to Use ',
    'yes': r'On',
}