# Generated by Django 3.0.5 on 2020-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Dashboard name.', max_length=255)),
                ('dashboard_model', models.TextField(help_text='JSON string for the dashboard.')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('panel_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('db_name', models.CharField(help_text='Database name in influxDB.', max_length=32)),
                ('query_str', models.TextField(help_text='Query string in querying language.')),
                ('panel_type', models.CharField(choices=[('BarChart', 'BarChart'), ('Histogram', 'Histogram'), ('LineChart', 'LineChart'), ('Gauge', 'Gauge'), ('Table', 'Table'), ('Heatmap', 'Heatmap'), ('PieChart', 'PieChart'), ('RingChart', 'RingChart'), ('ScatterChart', 'ScatterChart')], default='LineChart', help_text='Chart type.', max_length=32)),
                ('refresh', models.BooleanField(default=True, help_text='Return True if you want to refresh panel.')),
                ('refresh_interval', models.PositiveIntegerField(help_text='Refresh Interval (default: second).')),
                ('tag_name', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(help_text='Panel name.', max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
